### ISSUE TITLE
Connect the containers to an OVS bridge

### ISSUE THREAD

**Issue by TjWallas** [TjWallas/sandnet-migration-strategies#5]
### Abstract
Having installed ovs using the provisioning script in vagrant, our goal is to now:
1. Create a simple new OVS bridge
2. Spawn the containers and connect them to the OVS bridge
3. Make sure the containers can ping one another

### Useful links
http://containertutorials.com/network/ovs_docker.html
https://docs.docker.com/network/bridge/#use-ipv6-with-the-default-bridge-network

**Comment by JeannineBorn** [comment]
@TjWallas : i have connected 2 containers (container_br1 and container_br2) via OVS bridge. 
In the ip route table the addresses 173.16.1.0/24 and 172.17.0.0/16 were displayed, but when i exited the container and started it again with "sudo docker container start -i container_br1" the entry for the OVS-bridge was gone and only 172.17.0.0/16 remained.
This is probably because the ID of the container changes each time it is started again.
How can i make the ovs-br1 bridge remember the name of the container instead of the temporary ID?

![ovs_br1_bridge_and_container_container_br1](https://user-images.githubusercontent.com/11292639/37710902-67b8b856-2d0f-11e8-9eda-0b9a462e6e42.png)

**Comment by TjWallas** [comment]
@JeannineBorn Every time you start or stop a container, the name of the `veth` interface which acts as a virtual link between the default iface `eth0` within the container and the underlying bridge on the host (e.g. `docker0`, `ovs`) changes. Therefore, each time you start or stop a container, you need to manually detach the old ports from ovs and add attach the new `veth` ifaces to `ovs` instead. Simply running invoking the `ovs-docker` command again on the new container should help.
